### ISSUE TITLE
Hi, I'm new to this and the README is not helping alot.

### ISSUE THREAD

**Issue by sakuwuya** [core-hacked/Discondelete#4]
I'm running into this error:
C:\Users\Administrator\Discondelete>main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Discondelete\main.py", line 1, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

**Comment by core-hacked** [comment]
You need to install the requirements as said in the readme.
